-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- event triggers (packages/database/src/event-system/attachments.ts)
SET lock_timeout = '5s';
SELECT set_event_triggers('depreciationRun', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('depreciationRunLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('invoiceSettlement', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('journalLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('memo', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('pickingList', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('pickingListLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('reimbursementLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('revenueRecognitionRun', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('revenueRecognitionRunLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
RESET lock_timeout;
