-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- userAttribute
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userAttribute' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userAttribute');
  END LOOP;
END
$authz$;
ALTER TABLE public."userAttribute" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userAttribute" FOR SELECT USING (("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_view'))::text[])) OR ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])))));
CREATE POLICY "INSERT" ON "public"."userAttribute" FOR INSERT WITH CHECK ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."userAttribute" FOR UPDATE USING ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."userAttribute" FOR DELETE USING ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_delete'))::text[])));

-- userAttributeCategory
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userAttributeCategory' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userAttributeCategory');
  END LOOP;
END
$authz$;
ALTER TABLE public."userAttributeCategory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userAttributeCategory" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."userAttributeCategory" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."userAttributeCategory" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."userAttributeCategory" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_delete'))::text[]));

-- userAttributeValue
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userAttributeValue' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userAttributeValue');
  END LOOP;
END
$authz$;
ALTER TABLE public."userAttributeValue" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userAttributeValue" FOR SELECT USING ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
CREATE POLICY "INSERT" ON "public"."userAttributeValue" FOR INSERT WITH CHECK ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
CREATE POLICY "UPDATE" ON "public"."userAttributeValue" FOR UPDATE USING ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
CREATE POLICY "DELETE" ON "public"."userAttributeValue" FOR DELETE USING ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
