-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

CREATE OR REPLACE FUNCTION public.set_event_triggers(table_name_text text, before_functions text[] DEFAULT ARRAY[]::text[], after_functions text[] DEFAULT ARRAY[]::text[], queue_events boolean DEFAULT false, statement_functions text[] DEFAULT ARRAY[]::text[])
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  existing TEXT;
  fn_args TEXT;
  live TEXT[];
  wanted TEXT[];
BEGIN
  -- Makes a table's event triggers exactly what one entry of
  -- packages/database/src/event-system/attachments.ts says: the interceptors
  -- that run before and after each row, whether changes are queued as events,
  -- and the statement handlers. Called with only the table name, it detaches
  -- everything.

  -- A table dropped since its entry was shipped has nothing to attach to.
  IF to_regclass(format('public.%I', table_name_text)) IS NULL THEN
    RETURN;
  END IF;

  -- Already as declared: touch nothing. Creating a trigger locks the table
  -- against writes until the transaction ends, so a migration that restates
  -- every table's entry must not re-create the ones that have not changed.
  SELECT coalesce(array_agg(t.tgname || ':' || encode(t.tgargs, 'escape') ORDER BY t.tgname), '{}')
    INTO live
    FROM pg_trigger t
   WHERE t.tgrelid = format('public.%I', table_name_text)::regclass
     AND NOT t.tgisinternal
     AND t.tgname LIKE 'trg\_event\_%';

  SELECT coalesce(array_agg(w.name ORDER BY w.name), '{}')
    INTO wanted
    FROM (
      -- A trigger's arguments are stored NUL-terminated; a name is cut at 63 bytes.
      SELECT left('trg_event_sync_' || table_name_text, 63) || ':'
             || array_to_string(before_functions, '\000') || '\000'
       WHERE cardinality(before_functions) > 0
      UNION ALL
      SELECT left('trg_event_after_sync_' || table_name_text, 63) || ':'
             || array_to_string(after_functions, '\000') || '\000'
       WHERE cardinality(after_functions) > 0
      UNION ALL
      SELECT left('trg_event_async_' || op || '_' || table_name_text, 63) || ':'
        FROM unnest(ARRAY['ins', 'del', 'upd']) op
       WHERE queue_events
      UNION ALL
      SELECT left('trg_event_statement_' || fn || '_' || op, 63) || ':'
        FROM unnest(statement_functions) fn, unnest(ARRAY['ins', 'upd', 'del']) op
    ) w(name);

  IF live = wanted THEN
    RETURN;
  END IF;

  IF queue_events THEN
    PERFORM public.attach_event_trigger(table_name_text, before_functions, after_functions);
  ELSE
    -- attach_event_trigger always queues, so here the row-level triggers are
    -- created alone, with the same definitions it uses.
    FOR existing IN
      SELECT t.tgname
      FROM pg_trigger t
      WHERE t.tgrelid = format('public.%I', table_name_text)::regclass
        AND NOT t.tgisinternal
        AND (t.tgname LIKE 'trg\_event\_sync\_%'
          OR t.tgname LIKE 'trg\_event\_after\_sync\_%'
          OR t.tgname LIKE 'trg\_event\_async\_%')
    LOOP
      EXECUTE format('DROP TRIGGER IF EXISTS %2$I ON public.%1$I;', table_name_text, existing);
    END LOOP;

    IF array_length(before_functions, 1) > 0 THEN
      SELECT string_agg(quote_literal(x), ', ') INTO fn_args FROM unnest(before_functions) x;
      EXECUTE format('
        CREATE TRIGGER "trg_event_sync_%1$s"
        BEFORE INSERT OR UPDATE OR DELETE ON public.%1$I
        FOR EACH ROW
        EXECUTE FUNCTION public.dispatch_event_interceptors(%2$s);
      ', table_name_text, fn_args);
    END IF;

    IF array_length(after_functions, 1) > 0 THEN
      SELECT string_agg(quote_literal(x), ', ') INTO fn_args FROM unnest(after_functions) x;
      EXECUTE format('
        CREATE TRIGGER "trg_event_after_sync_%1$s"
        AFTER INSERT OR UPDATE OR DELETE ON public.%1$I
        FOR EACH ROW
        EXECUTE FUNCTION public.dispatch_event_after_interceptors(%2$s);
      ', table_name_text, fn_args);
    END IF;
  END IF;

  PERFORM public.attach_statement_handler(table_name_text, statement_functions);
END;
$function$;

CREATE OR REPLACE FUNCTION public.apply_item_stock_quantities()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO "itemStockQuantities" AS isq
      ("itemId", "companyId", "locationId", "quantityOnHand")
    SELECT
      "itemId",
      "companyId",
      COALESCE("locationId", ''),
      SUM(item_ledger_on_hand_contribution("quantity", "trackedEntityStatus"))
    FROM batched_new
    GROUP BY "itemId", "companyId", COALESCE("locationId", '')
    ORDER BY 1, 2, 3
    ON CONFLICT ("itemId", "companyId", "locationId")
    DO UPDATE SET "quantityOnHand" = isq."quantityOnHand" + EXCLUDED."quantityOnHand";

  ELSIF TG_OP = 'UPDATE' THEN
    -- Generic old-vs-new: subtract every old row's contribution at its old key
    -- and add every new row's at its new key. Covers the real case (a
    -- trackedEntityStatus flip) and any future quantity/location/item edit
    -- without special-casing.
    INSERT INTO "itemStockQuantities" AS isq
      ("itemId", "companyId", "locationId", "quantityOnHand")
    SELECT "itemId", "companyId", "locationId", SUM(delta)
    FROM (
      SELECT
        "itemId",
        "companyId",
        COALESCE("locationId", '') AS "locationId",
        -item_ledger_on_hand_contribution("quantity", "trackedEntityStatus") AS delta
      FROM batched_old
      UNION ALL
      SELECT
        "itemId",
        "companyId",
        COALESCE("locationId", ''),
        item_ledger_on_hand_contribution("quantity", "trackedEntityStatus")
      FROM batched_new
    ) d
    GROUP BY "itemId", "companyId", "locationId"
    -- A key whose net delta is zero already holds the right number; skipping it
    -- avoids taking a lock on every row a wide UPDATE happened to touch.
    HAVING SUM(delta) <> 0
    ORDER BY 1, 2, 3
    ON CONFLICT ("itemId", "companyId", "locationId")
    DO UPDATE SET "quantityOnHand" = isq."quantityOnHand" + EXCLUDED."quantityOnHand";

  ELSIF TG_OP = 'DELETE' THEN
    -- Defensive: no application path deletes itemLedger rows today. A key left
    -- at zero with no backing ledger rows is removed by the nightly
    -- reconciliation.
    INSERT INTO "itemStockQuantities" AS isq
      ("itemId", "companyId", "locationId", "quantityOnHand")
    SELECT
      "itemId",
      "companyId",
      COALESCE("locationId", ''),
      -SUM(item_ledger_on_hand_contribution("quantity", "trackedEntityStatus"))
    FROM batched_old
    GROUP BY "itemId", "companyId", COALESCE("locationId", '')
    ORDER BY 1, 2, 3
    ON CONFLICT ("itemId", "companyId", "locationId")
    DO UPDATE SET "quantityOnHand" = isq."quantityOnHand" + EXCLUDED."quantityOnHand";
  END IF;

  RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_posted_purchase_invoice_deletion(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation = 'DELETE' THEN
    IF NOT EXISTS (SELECT 1 FROM "company" WHERE id = (p_old->>'companyId')) THEN
      RETURN;
    END IF;
    IF p_old->>'status' IS DISTINCT FROM 'Draft' THEN
      RAISE EXCEPTION 'Cannot delete purchase invoice with status "%". Only Draft invoices can be deleted.', p_old->>'status';
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.prevent_posted_sales_invoice_deletion(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation = 'DELETE' THEN
    IF NOT EXISTS (SELECT 1 FROM "company" WHERE id = (p_old->>'companyId')) THEN
      RETURN;
    END IF;
    IF p_old->>'status' IS DISTINCT FROM 'Draft' THEN
      RAISE EXCEPTION 'Cannot delete sales invoice with status "%". Only Draft invoices can be deleted.', p_old->>'status';
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_shelf_life_on_operation_done(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_old_status TEXT;
  v_new_status TEXT;
BEGIN
  IF p_operation <> 'UPDATE' THEN
    RETURN;
  END IF;

  v_new_status := p_new->>'status';
  IF v_new_status <> 'Done' THEN
    RETURN;
  END IF;

  v_old_status := p_old->>'status';
  IF v_old_status = 'Done' THEN
    RETURN;
  END IF;

  PERFORM set_shelf_life_for_operation(p_new->>'id', 'After');
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_shelf_life_on_operation_started(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_old_status TEXT;
  v_new_status TEXT;
BEGIN
  IF p_operation <> 'UPDATE' THEN
    RETURN;
  END IF;

  v_new_status := p_new->>'status';
  IF v_new_status <> 'In Progress' THEN
    RETURN;
  END IF;

  v_old_status := p_old->>'status';
  IF v_old_status = 'In Progress' THEN
    RETURN;
  END IF;

  PERFORM set_shelf_life_for_operation(p_new->>'id', 'Before');
END;
$function$;

CREATE OR REPLACE FUNCTION public.storage_unit_block_location_change_with_children(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_id              TEXT;
  v_new_location    TEXT;
  v_old_location    TEXT;
BEGIN
  IF p_operation <> 'UPDATE' THEN
    RETURN;
  END IF;

  v_new_location := p_new->>'locationId';
  v_old_location := p_old->>'locationId';

  IF v_new_location IS NOT DISTINCT FROM v_old_location THEN
    RETURN;
  END IF;

  v_id := p_old->>'id';

  IF EXISTS (SELECT 1 FROM "storageUnit" WHERE "parentId" = v_id) THEN
    RAISE EXCEPTION
      'Cannot change locationId of storage unit % because it has child units',
      v_id;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.storage_unit_enforce_no_cycle(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_self_id   TEXT;
  v_cursor_id TEXT;
  v_depth     INTEGER := 0;
BEGIN
  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN
    RETURN;
  END IF;

  v_cursor_id := p_new->>'parentId';
  IF v_cursor_id IS NULL THEN
    RETURN;
  END IF;

  v_self_id := p_new->>'id';

  WHILE v_cursor_id IS NOT NULL LOOP
    IF v_cursor_id = v_self_id THEN
      RAISE EXCEPTION 'Cycle detected in storage unit hierarchy at %', v_self_id;
    END IF;

    v_depth := v_depth + 1;
    IF v_depth > 1000 THEN
      RAISE EXCEPTION 'Storage unit hierarchy exceeds max depth (possible cycle)';
    END IF;

    SELECT "parentId" INTO v_cursor_id
    FROM "storageUnit"
    WHERE "id" = v_cursor_id;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.storage_unit_enforce_same_location(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_parent_id       TEXT;
  v_parent_location TEXT;
  v_new_location    TEXT;
BEGIN
  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN
    RETURN;
  END IF;

  v_parent_id := p_new->>'parentId';
  IF v_parent_id IS NULL THEN
    RETURN;
  END IF;

  v_new_location := p_new->>'locationId';

  SELECT "locationId"
  INTO v_parent_location
  FROM "storageUnit"
  WHERE "id" = v_parent_id;

  IF v_parent_location IS NULL THEN
    RAISE EXCEPTION 'Parent storage unit % does not exist', v_parent_id;
  END IF;

  IF v_parent_location <> v_new_location THEN
    RAISE EXCEPTION
      'Parent storage unit % is in location %, but this unit is in location %; they must match',
      v_parent_id, v_parent_location, v_new_location;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_add_customer_account_to_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "membership" ("groupId", "memberUserId")
  VALUES (
    p_new->>'customerId',
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_add_employee_to_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "membership" ("groupId", "memberUserId")
  VALUES (
    p_new->>'employeeTypeId',
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_add_supplier_account_to_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "membership" ("groupId", "memberUserId")
  VALUES (
    p_new->>'supplierId',
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_address_to_parent(table_name text, operation text, new_data jsonb, old_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  address_id TEXT;
BEGIN
  IF operation = 'DELETE' THEN
    RETURN;
  END IF;

  IF current_setting('app.sync_in_progress', true) = 'true' THEN
    RETURN;
  END IF;

  address_id := COALESCE(new_data->>'id', old_data->>'id');

  UPDATE "customer" c
  SET "updatedAt" = NOW()
  FROM "customerLocation" cl
  WHERE cl."addressId" = address_id
    AND cl."customerId" = c.id;

  UPDATE "supplier" s
  SET "updatedAt" = NOW()
  FROM "supplierLocation" sl
  WHERE sl."addressId" = address_id
    AND sl."supplierId" = s.id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_archive_other_procedures(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF NOT ((p_new->>'status') = 'Active' AND ((p_old->>'status') IS NULL OR (p_old->>'status') != 'Active')) THEN
    RETURN;
  END IF;

  UPDATE procedure
  SET status = 'Archived'
  WHERE name = p_new->>'name'
    AND "companyId" = p_new->>'companyId'
    AND id != p_new->>'id'
    AND status = 'Active';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_archive_other_quality_documents(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF NOT ((p_new->>'status') = 'Active' AND ((p_old->>'status') IS NULL OR (p_old->>'status') != 'Active')) THEN
    RETURN;
  END IF;

  UPDATE "qualityDocument"
  SET status = 'Archived'
  WHERE name = p_new->>'name'
    AND "companyId" = p_new->>'companyId'
    AND id != p_new->>'id'
    AND status = 'Active';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_check_job_material_self_reference(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  job_item_id TEXT;
BEGIN
  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN RETURN; END IF;

  SELECT "itemId" INTO job_item_id
  FROM job
  WHERE "id" = p_new->>'jobId'
    AND "companyId" = p_new->>'companyId';

  IF job_item_id = p_new->>'itemId' THEN
    RAISE EXCEPTION 'A job cannot consume the item it produces as a material'
      USING ERRCODE = 'check_violation';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_check_method_material_self_reference(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  parent_item_id TEXT;
  cycle_found BOOLEAN;
BEGIN
  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN RETURN; END IF;

  -- A make method belongs to exactly one item, so a materialMakeMethodId equal
  -- to the row's own makeMethodId is always a self-loop regardless of itemId.
  IF p_new->>'materialMakeMethodId' = p_new->>'makeMethodId' THEN
    RAISE EXCEPTION 'An item cannot use its own make method as a material sub-method'
      USING ERRCODE = 'check_violation';
  END IF;

  SELECT "itemId" INTO parent_item_id
  FROM "makeMethod"
  WHERE "id" = p_new->>'makeMethodId'
    AND "companyId" = p_new->>'companyId';

  IF parent_item_id = p_new->>'itemId' THEN
    RAISE EXCEPTION 'An item cannot be a material on its own bill of materials'
      USING ERRCODE = 'check_violation';
  END IF;

  -- Multi-node cycles (A needs B, B needs A): would the new material's own
  -- active-method BOM graph reach back to this method's item? Bounded walk
  -- over active methods only — the graph MRP plans against. UNION (not UNION
  -- ALL) dedupes, so the walk terminates even over pre-existing cycles; the
  -- depth cap is a backstop. BOM edits are UI-volume, so the walk is cheap.
  WITH RECURSIVE reachable AS (
    SELECT p_new->>'itemId' AS item_id, 0 AS depth
    UNION
    SELECT mm."itemId", r.depth + 1
    FROM reachable r
    JOIN "activeMakeMethods" amm
      ON amm."itemId" = r.item_id
     AND amm."companyId" = p_new->>'companyId'
    JOIN "methodMaterial" mm
      ON mm."makeMethodId" = amm."id"
     AND mm."companyId" = amm."companyId"
    WHERE r.depth < 100
  )
  SELECT EXISTS (SELECT 1 FROM reachable WHERE item_id = parent_item_id)
  INTO cycle_found;

  IF cycle_found THEN
    RAISE EXCEPTION 'Adding this material would create a loop in the bill of materials: its own BOM already contains this item'
      USING ERRCODE = 'check_violation';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_contact_to_parent(table_name text, operation text, new_data jsonb, old_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  contact_id TEXT;
BEGIN
  IF operation = 'DELETE' THEN
    RETURN;
  END IF;

  IF current_setting('app.sync_in_progress', true) = 'true' THEN
    RETURN;
  END IF;

  contact_id := COALESCE(new_data->>'id', old_data->>'id');

  UPDATE "customer" c
  SET "updatedAt" = NOW()
  FROM "customerContact" cc
  WHERE cc."contactId" = contact_id
    AND cc."customerId" = c.id;

  UPDATE "supplier" s
  SET "updatedAt" = NOW()
  FROM "supplierContact" sc
  WHERE sc."contactId" = contact_id
    AND sc."supplierId" = s.id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_customer_entries(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "customerPayment"("customerId", "invoiceCustomerId", "companyId")
  VALUES (p_new->>'id', p_new->>'id', p_new->>'companyId');

  INSERT INTO "customerShipping"("customerId", "shippingCustomerId", "companyId")
  VALUES (p_new->>'id', p_new->>'id', p_new->>'companyId');

  INSERT INTO "customerTax"("customerId", "companyId")
  VALUES (p_new->>'id', p_new->>'companyId');
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_customer_org_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "group" ("id", "name", "isCustomerOrgGroup", "companyId")
  VALUES (p_new->>'id', p_new->>'name', TRUE, p_new->>'companyId');

  IF p_new->>'customerTypeId' IS NOT NULL THEN
    INSERT INTO "membership"("groupId", "memberGroupId")
    VALUES (p_new->>'customerTypeId', p_new->>'id');
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_customer_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "group" ("id", "name", "isCustomerTypeGroup", "companyId")
  VALUES (
    p_new->>'id',
    p_new->>'name',
    TRUE,
    p_new->>'companyId'
  );

  INSERT INTO "membership" ("groupId", "memberGroupId")
  VALUES (
    '11111111-1111-'
      || substring((p_new->>'companyId')::text, 1, 4) || '-'
      || substring((p_new->>'companyId')::text, 5, 4) || '-'
      || substring((p_new->>'companyId')::text, 9, 12),
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_employee_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "group" ("id", "name", "isEmployeeTypeGroup", "companyId")
  VALUES (
    p_new->>'id',
    p_new->>'name',
    TRUE,
    p_new->>'companyId'
  );

  INSERT INTO "membership" ("groupId", "memberGroupId")
  VALUES (
    '00000000-0000-'
      || substring((p_new->>'companyId')::text, 1, 4) || '-'
      || substring((p_new->>'companyId')::text, 5, 4) || '-'
      || substring((p_new->>'companyId')::text, 9, 12),
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_item_related_records(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  base_currency TEXT;
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  SELECT "baseCurrencyCode"
  INTO base_currency
  FROM "company"
  WHERE "id" = p_new->>'companyId';

  INSERT INTO "itemCost"("itemId", "costingMethod", "createdBy", "companyId")
  VALUES (p_new->>'id', 'FIFO', p_new->>'createdBy', p_new->>'companyId');

  INSERT INTO "itemReplenishment"("itemId", "createdBy", "companyId")
  VALUES (p_new->>'id', p_new->>'createdBy', p_new->>'companyId');

  INSERT INTO "itemUnitSalePrice"("itemId", "currencyCode", "createdBy", "companyId")
  VALUES (p_new->>'id', COALESCE(base_currency, 'USD'), p_new->>'createdBy', p_new->>'companyId');

  INSERT INTO "itemPlanning"("itemId", "locationId", "createdBy", "companyId")
  SELECT
    p_new->>'id',
    l.id,
    p_new->>'createdBy',
    p_new->>'companyId'
  FROM "location" l
  WHERE l."companyId" = p_new->>'companyId';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_location_related_records(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  -- Only create itemPlanning records for the new location
  -- Skip the postingGroupInventory inserts since that table no longer exists
  INSERT INTO "itemPlanning" ("itemId", "locationId", "createdBy", "companyId", "createdAt", "updatedAt")
  SELECT
    i.id AS "itemId",
    p_new->>'id' AS "locationId",
    i."createdBy",
    i."companyId",
    NOW(),
    NOW()
  FROM "item" i
  WHERE i."companyId" = p_new->>'companyId';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_make_method_related_records(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  IF (p_new->>'type') IN ('Part', 'Tool', 'Service') THEN
    INSERT INTO "makeMethod"("itemId", "createdBy", "companyId")
    VALUES (p_new->>'id', p_new->>'createdBy', p_new->>'companyId');
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_nc_external_link(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_external_link_id UUID;
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "externalLink" ("documentType", "documentId", "companyId")
  VALUES ('Non-Conformance Supplier', p_new->>'id', p_new->>'companyId')
  ON CONFLICT ("documentId", "documentType", "companyId") DO UPDATE SET
    "documentType" = EXCLUDED."documentType"
  RETURNING "id" INTO v_external_link_id;

  UPDATE "nonConformanceSupplier"
  SET "externalLinkId" = v_external_link_id
  WHERE "id" = p_new->>'id';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_supplier_entries(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "supplierPayment"("supplierId", "invoiceSupplierId", "companyId")
  VALUES (p_new->>'id', p_new->>'id', p_new->>'companyId');

  INSERT INTO "supplierShipping"("supplierId", "shippingSupplierId", "companyId")
  VALUES (p_new->>'id', p_new->>'id', p_new->>'companyId');

  INSERT INTO "supplierTax"("supplierId", "companyId")
  VALUES (p_new->>'id', p_new->>'companyId');
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_supplier_org_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "group" ("id", "name", "isSupplierOrgGroup", "companyId")
  VALUES (p_new->>'id', p_new->>'name', TRUE, p_new->>'companyId');

  IF p_new->>'supplierTypeId' IS NOT NULL THEN
    INSERT INTO "membership"("groupId", "memberGroupId")
    VALUES (p_new->>'supplierTypeId', p_new->>'id');
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_supplier_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "group" ("id", "name", "isSupplierTypeGroup", "companyId")
  VALUES (
    p_new->>'id',
    p_new->>'name',
    TRUE,
    p_new->>'companyId'
  );

  INSERT INTO "membership" ("groupId", "memberGroupId")
  VALUES (
    '22222222-2222-'
      || substring((p_new->>'companyId')::text, 1, 4) || '-'
      || substring((p_new->>'companyId')::text, 5, 4) || '-'
      || substring((p_new->>'companyId')::text, 9, 12),
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_create_user_identity_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "group" ("id", "name", "isIdentityGroup")
  VALUES (
    p_new->>'id',
    p_new->>'fullName',
    TRUE
  );

  INSERT INTO "membership" ("groupId", "memberUserId")
  VALUES (
    p_new->>'id',
    p_new->>'id'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_delete_tracked_entity_on_job_make_method(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'DELETE' THEN RETURN; END IF;

  DELETE FROM "trackedEntity"
  WHERE "attributes"->>'Job Make Method' = p_old->>'id';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_delete_user_identity_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'DELETE' THEN RETURN; END IF;

  DELETE FROM "group"
  WHERE "id" = p_old->>'id'
    AND "isIdentityGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_edit_document_transaction(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  INSERT INTO "documentTransaction" ("documentId", "type", "userId")
  VALUES (p_new->>'id', 'Edit', p_new->>'createdBy');
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_finish_job_operation(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_job_location_id TEXT;
  v_job_storage_unit_id TEXT;
  v_job_quantity NUMERIC;
  v_sales_order_id TEXT;
  v_quantity_complete NUMERIC;
  v_quantity_lost NUMERIC;
  v_quantity_received NUMERIC;
  v_job_status TEXT;
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF (p_new->>'status') != 'Done' OR (p_old->>'status') = 'Done' THEN RETURN; END IF;

  UPDATE "productionEvent"
  SET "endTime" = NOW()
  WHERE "jobOperationId" = p_new->>'id'
    AND "endTime" IS NULL;

  UPDATE "jobOperation" op
  SET status = 'Ready'
  WHERE EXISTS (
    SELECT 1
    FROM "jobOperationDependency" dep
    WHERE dep."operationId" = op.id
      AND dep."dependsOnId" = p_new->>'id'
      AND op.status = 'Waiting'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM "jobOperationDependency" dep2
    JOIN "jobOperation" jo2 ON jo2.id = dep2."dependsOnId"
    WHERE dep2."operationId" = op.id
      AND jo2.status != 'Done'
      AND jo2.id != p_new->>'id'
  );

  SELECT status INTO v_job_status FROM "job" WHERE id = p_new->>'jobId';
  -- A Draft/Planned job's operation can only reach Done through a released
  -- BATCH (batch release outranks job release for floor visibility), so the
  -- run genuinely happened. Completing the batch must complete those jobs
  -- too: otherwise their output lots exist while their receipts never post,
  -- and a merged output lot carries only the received fraction of its
  -- quantity.
  IF v_job_status NOT IN ('Ready', 'In Progress', 'Paused')
     AND NOT (
       (p_new->>'jobOperationBatchId') IS NOT NULL
       AND v_job_status IN ('Draft', 'Planned')
     ) THEN
    RETURN;
  END IF;

  IF is_last_job_operation(p_new->>'id') THEN
    SELECT "locationId", "storageUnitId", quantity, "salesOrderId", "quantityReceivedToInventory"
    INTO v_job_location_id, v_job_storage_unit_id, v_job_quantity, v_sales_order_id, v_quantity_received
    FROM "job"
    WHERE id = p_new->>'jobId';

    v_quantity_complete := (
      SELECT COALESCE(SUM(terminal_jo."quantityComplete"), 0)
      FROM "jobOperation" terminal_jo
      INNER JOIN "jobMakeMethod" terminal_jmm ON terminal_jmm.id = terminal_jo."jobMakeMethodId"
      WHERE terminal_jo."jobId" = p_new->>'jobId'
        AND terminal_jmm."parentMaterialId" IS NULL
        AND NOT EXISTS (
          SELECT 1
          FROM "jobOperationDependency" dep
          INNER JOIN "jobOperation" child_jo ON child_jo.id = dep."operationId"
          INNER JOIN "jobMakeMethod" child_jmm ON child_jmm.id = child_jo."jobMakeMethodId"
          WHERE dep."dependsOnId" = terminal_jo.id
            AND child_jmm."parentMaterialId" IS NULL
        )
    );

    IF COALESCE(v_quantity_complete, 0) = 0 THEN
      -- The zero fallback exists for the quantity-less Finish flow (no
      -- productionQuantity ever recorded). When the job DID record scrap or
      -- rework, zero completions is a real outcome (e.g. a fully-scrapped
      -- lot) — falling back would receive scrapped units into stock.
      SELECT COALESCE(SUM(COALESCE("quantityScrapped", 0) + COALESCE("quantityReworked", 0)), 0)
      INTO v_quantity_lost
      FROM "jobOperation"
      WHERE "jobId" = p_new->>'jobId';

      IF v_quantity_lost = 0 THEN
        v_quantity_complete := v_job_quantity;
      ELSE
        -- Nothing to receive: close the job without posting Assembly Output.
        -- Materials were already consumed by the scrap/complete flows; WIP
        -- cost disposition for fully-scrapped jobs is a costing follow-up.
        UPDATE "job"
        SET status = 'Completed',
            "completedDate" = NOW(),
            "quantityComplete" = 0,
            "updatedBy" = COALESCE(p_new->>'updatedBy', p_new->>'createdBy'),
            "updatedAt" = NOW()
        WHERE id = p_new->>'jobId';
        RETURN;
      END IF;
    END IF;

    -- A reopened job may already have received more than its operations now
    -- report. complete_job_to_inventory refuses a quantity below what was
    -- received, and refusing here would block the Done update itself.
    v_quantity_complete := GREATEST(v_quantity_complete, COALESCE(v_quantity_received, 0));

    PERFORM complete_job_to_inventory(
      p_job_id := p_new->>'jobId',
      p_quantity_complete := v_quantity_complete,
      p_storage_unit_id := v_job_storage_unit_id,
      p_location_id := v_job_location_id,
      p_company_id := p_new->>'companyId',
      p_user_id := COALESCE(p_new->>'updatedBy', p_new->>'createdBy')
    );
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_insert_company_related_records(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "terms" ("id")
  VALUES (p_new->>'id');

  INSERT INTO "companySettings" ("id")
  VALUES (p_new->>'id');
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_insert_job_make_method(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_item_readable_id TEXT;
  v_item_tracking_type TEXT;
  v_job_make_method_id TEXT;
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  SELECT "readableIdWithRevision", "itemTrackingType"
    INTO v_item_readable_id, v_item_tracking_type
  FROM "item"
  WHERE "id" = p_new->>'itemId';

  INSERT INTO "jobMakeMethod" (
    "jobId", "itemId", "companyId", "createdBy",
    "requiresSerialTracking", "requiresBatchTracking"
  ) VALUES (
    p_new->>'id', p_new->>'itemId', p_new->>'companyId', p_new->>'createdBy',
    v_item_tracking_type = 'Serial', v_item_tracking_type = 'Batch'
  )
  RETURNING "id" INTO v_job_make_method_id;

  INSERT INTO "trackedEntity" (
    "sourceDocument", "sourceDocumentId", "sourceDocumentReadableId",
    "quantity", "status", "companyId", "createdBy", "attributes", "itemId"
  ) VALUES (
    'Item', p_new->>'itemId', v_item_readable_id,
    COALESCE((p_new->>'quantity')::numeric, 1), 'Reserved',
    p_new->>'companyId', p_new->>'createdBy',
    jsonb_build_object('Job', p_new->>'id', 'Job Make Method', v_job_make_method_id),
    p_new->>'itemId'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_insert_job_material_make_method(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_item_readable_id TEXT;
  v_item_tracking_type TEXT;
  v_job_make_method_id TEXT;
  v_version NUMERIC(10, 2);
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;
  IF (p_new->>'methodType') != 'Make to Order' THEN RETURN; END IF;
  IF (p_new->>'itemId') IS NULL THEN RETURN; END IF;

  SELECT "readableIdWithRevision", "itemTrackingType"
    INTO v_item_readable_id, v_item_tracking_type
  FROM "item"
  WHERE "id" = p_new->>'itemId';

  SELECT "version" INTO v_version FROM "activeMakeMethods" WHERE "itemId" = p_new->>'itemId';

  INSERT INTO "jobMakeMethod" (
    "jobId", "parentMaterialId", "itemId", "companyId", "createdBy",
    "requiresSerialTracking", "requiresBatchTracking", "version"
  ) VALUES (
    p_new->>'jobId', p_new->>'id', p_new->>'itemId', p_new->>'companyId', p_new->>'createdBy',
    v_item_tracking_type = 'Serial', v_item_tracking_type = 'Batch', v_version
  )
  RETURNING "id" INTO v_job_make_method_id;

  INSERT INTO "trackedEntity" (
    "sourceDocument", "sourceDocumentId", "sourceDocumentReadableId",
    "quantity", "status", "companyId", "createdBy", "attributes", "itemId"
  ) VALUES (
    'Item', p_new->>'itemId', v_item_readable_id,
    (p_new->>'quantity')::numeric, 'Reserved',
    p_new->>'companyId', p_new->>'createdBy',
    jsonb_build_object('Job', p_new->>'jobId', 'Job Make Method', v_job_make_method_id, 'Job Material', p_new->>'id'),
    p_new->>'itemId'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_insert_quote_line_make_method(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_version NUMERIC(10, 2);
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;
  IF (p_new->>'methodType') != 'Make to Order' THEN RETURN; END IF;
  IF (p_new->>'itemId') IS NULL THEN RETURN; END IF;

  SELECT "version" INTO v_version FROM "activeMakeMethods" WHERE "itemId" = p_new->>'itemId';

  INSERT INTO "quoteMakeMethod" (
    "quoteId", "quoteLineId", "itemId", "companyId", "createdAt", "createdBy", "version"
  ) VALUES (
    p_new->>'quoteId', p_new->>'id', p_new->>'itemId',
    p_new->>'companyId', NOW(), p_new->>'createdBy', v_version
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_insert_quote_material_make_method(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_version NUMERIC(10, 2);
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;
  IF (p_new->>'methodType') != 'Make to Order' THEN RETURN; END IF;
  IF (p_new->>'itemId') IS NULL THEN RETURN; END IF;

  SELECT "version" INTO v_version FROM "activeMakeMethods" WHERE "itemId" = p_new->>'itemId';

  INSERT INTO "quoteMakeMethod" (
    "quoteId", "quoteLineId", "parentMaterialId", "itemId", "companyId", "createdAt", "createdBy", "version"
  ) VALUES (
    p_new->>'quoteId', p_new->>'quoteLineId', p_new->>'id', p_new->>'itemId',
    p_new->>'companyId', NOW(), p_new->>'createdBy', v_version
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_job_complete_or_canceled(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  group_ids TEXT[];
BEGIN
  IF p_operation = 'UPDATE'
    AND (p_old->>'status') != (p_new->>'status')
    AND ((p_new->>'status') = 'Completed' OR (p_new->>'status') = 'Cancelled')
  THEN
    UPDATE "kanban"
    SET "jobId" = NULL
    WHERE "jobId" = p_new->>'id';

    -- Send notification on job completion
    IF (p_new->>'status') = 'Completed' THEN
      IF (p_new->>'salesOrderId') IS NULL THEN
        SELECT "inventoryJobCompletedNotificationGroup" INTO group_ids
        FROM "companySettings" WHERE "id" = p_new->>'companyId';
      ELSE
        SELECT "salesJobCompletedNotificationGroup" INTO group_ids
        FROM "companySettings" WHERE "id" = p_new->>'companyId';
      END IF;

      IF (p_new->>'assignee') IS NOT NULL THEN
        group_ids := array_append(COALESCE(group_ids, '{}'), p_new->>'assignee');
      END IF;

      IF array_length(group_ids, 1) > 0 THEN
        PERFORM util.send_inngest_event(
          'carbon/notify',
          jsonb_build_object(
            'companyId', p_new->>'companyId',
            'documentId', p_new->>'id',
            'event', 'job-completed',
            'recipient', jsonb_build_object(
              'type', 'group',
              'groupIds', group_ids
            ),
            'from', 'system'
          )
        );
      END IF;
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_job_recompute_service_line(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF (p_new->>'salesOrderLineId') IS NULL THEN RETURN; END IF;

  -- Only when the completion state actually changed.
  IF (p_old->>'status') IS NOT DISTINCT FROM (p_new->>'status') THEN RETURN; END IF;
  IF NOT (
    (p_old->>'status') IN ('Completed', 'Closed')
    OR (p_new->>'status') IN ('Completed', 'Closed')
  ) THEN
    RETURN;
  END IF;

  PERFORM recompute_service_line_fulfillment(
    p_new->>'salesOrderLineId',
    p_new->>'companyId',
    p_new->>'updatedBy'
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_on_maintenance_dispatch_complete(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF NOT ((p_new->>'status') = 'Completed' AND ((p_old->>'status') IS NULL OR (p_old->>'status') != 'Completed')) THEN
    RETURN;
  END IF;

  -- End all active events for this dispatch
  UPDATE "maintenanceDispatchEvent"
  SET
    "endTime" = COALESCE((p_new->>'completedAt')::timestamptz, NOW()),
    "updatedBy" = p_new->>'updatedBy',
    "updatedAt" = NOW()
  WHERE
    "maintenanceDispatchId" = p_new->>'id'
    AND "endTime" IS NULL;

  -- Set actualEndTime if not already set
  IF (p_new->>'actualEndTime') IS NULL THEN
    UPDATE "maintenanceDispatch"
    SET
      "actualEndTime" = NOW(),
      "updatedBy" = p_new->>'updatedBy',
      "updatedAt" = NOW()
    WHERE id = p_new->>'id';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_propagate_item_readable_id_to_tracked_entity(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF (p_new->>'readableIdWithRevision') IS NOT DISTINCT FROM (p_old->>'readableIdWithRevision') THEN
    RETURN;
  END IF;

  UPDATE "trackedEntity"
  SET "sourceDocumentReadableId" = p_new->>'readableIdWithRevision'
  WHERE "sourceDocument" = 'Item'
    AND "sourceDocumentId" = p_new->>'id';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_protect_system_required_actions(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation = 'DELETE' THEN
    IF (p_old->>'systemType') IS NOT NULL THEN
      -- Allow cascading deletes when the parent company is being deleted
      IF NOT EXISTS (SELECT 1 FROM "company" WHERE id = p_old->>'companyId') THEN
        RETURN;
      END IF;
      RAISE EXCEPTION 'Cannot delete a system-defined required action. You may deactivate it instead.';
    END IF;
  END IF;

  IF p_operation = 'UPDATE' THEN
    IF (p_old->>'systemType') IS NOT NULL AND (p_new->>'systemType') IS DISTINCT FROM (p_old->>'systemType') THEN
      RAISE EXCEPTION 'Cannot change the systemType of a system-defined required action.';
    END IF;
    IF (p_old->>'systemType') IS NULL AND (p_new->>'systemType') IS NOT NULL THEN
      RAISE EXCEPTION 'Cannot assign a systemType to a custom required action.';
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_purchase_invoice_line_price_change(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation = 'UPDATE'
     AND ((p_new->>'unitPrice') IS DISTINCT FROM (p_old->>'unitPrice')
       OR (p_new->>'quantity') IS DISTINCT FROM (p_old->>'quantity'))
  THEN
    INSERT INTO "purchaseInvoicePriceChange" (
      "invoiceId", "invoiceLineId", "previousPrice", "newPrice",
      "previousQuantity", "newQuantity", "updatedBy"
    ) VALUES (
      p_new->>'invoiceId', p_new->>'id',
      (p_old->>'unitPrice')::numeric, (p_new->>'unitPrice')::numeric,
      (p_old->>'quantity')::numeric, (p_new->>'quantity')::numeric,
      COALESCE(p_new->>'updatedBy', p_new->>'createdBy')
    );
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_set_initial_dependency_status(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  -- Don't update if operation is already Done, In Progress, or Canceled
  IF EXISTS (
    SELECT 1
    FROM "jobOperation"
    WHERE id = p_new->>'operationId'
      AND status IN ('Done', 'In Progress', 'Canceled')
  ) THEN
    RETURN;
  END IF;

  -- Check if there are any incomplete dependencies
  IF EXISTS (
    SELECT 1
    FROM "jobOperationDependency" dep
    JOIN "jobOperation" jo ON jo.id = dep."dependsOnId"
    WHERE dep."operationId" = p_new->>'operationId'
      AND jo.status != 'Done'
  ) THEN
    UPDATE "jobOperation"
    SET status = 'Waiting'
    WHERE id = p_new->>'operationId';
  ELSE
    UPDATE "jobOperation"
    SET status = 'Ready'
    WHERE id = p_new->>'operationId';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_set_job_operation_in_progress(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  -- Only set to In Progress if endTime is NULL (event is starting, not already ended)
  IF (p_new->>'endTime') IS NULL THEN
    UPDATE "jobOperation"
    SET "status" = 'In Progress'
    WHERE id = p_new->>'jobOperationId';
  END IF;

  -- Set parent job to In Progress if it is still Ready
  UPDATE "job"
  SET "status" = 'In Progress'
  WHERE id = (
    SELECT "jobId" FROM "jobOperation" WHERE id = p_new->>'jobOperationId'
  )
  AND "status" = 'Ready';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_customer_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  IF p_old->>'customerTypeId' IS NOT NULL THEN
    IF p_new->>'customerTypeId' IS NOT NULL THEN
      UPDATE "membership" SET "groupId" = p_new->>'customerTypeId'
      WHERE "groupId" = p_old->>'customerTypeId' AND "memberGroupId" = p_new->>'id';
    ELSE
      DELETE FROM "membership"
      WHERE "groupId" = p_old->>'customerTypeId' AND "memberGroupId" = p_new->>'id';
    END IF;
  ELSE
    IF p_new->>'customerTypeId' IS NOT NULL THEN
      INSERT INTO "membership" ("groupId", "memberGroupId")
      VALUES (p_new->>'customerTypeId', p_new->>'id');
    END IF;
  END IF;

  UPDATE "group" SET "name" = p_new->>'name'
  WHERE "id" = p_new->>'id' AND "isCustomerOrgGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_customer_type_group_name(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  UPDATE "group"
  SET "name" = p_new->>'name'
  WHERE "id" = p_new->>'id'
    AND "isCustomerTypeGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_employee_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  UPDATE "group"
  SET "name" = p_new->>'name'
  WHERE "id" = p_new->>'id'
    AND "isEmployeeTypeGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_employee_type_membership(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  UPDATE "membership"
  SET "groupId" = p_new->>'employeeTypeId'
  WHERE "groupId" = p_old->>'employeeTypeId'
    AND "memberUserId" = p_new->>'id';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_job_material_make_method_item_id(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_item_readable_id TEXT;
  v_item_tracking_type TEXT;
  v_job_make_method_id TEXT;
  -- Bare NUMERIC: the repo bans a precision spec on NUMERIC, and the
  -- conformance gate scans migration TEXT — so carrying the original
  -- declaration's precision forward registered as a new violation (as does
  -- quoting it in a comment). Behaviour is identical: makeMethod.version is
  -- itself a constrained numeric, so the value round-trips through this local
  -- unchanged and lands back in the same column.
  v_version NUMERIC;
  v_attributes JSONB;
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  IF NOT (
    ((p_old->>'methodType') = 'Make to Order' AND (p_old->>'itemId') IS DISTINCT FROM (p_new->>'itemId'))
    OR ((p_new->>'methodType') = 'Make to Order' AND (p_old->>'methodType') != 'Make to Order')
  ) THEN
    RETURN;
  END IF;

  -- Both lookups are company-scoped: "item" is keyed ("id", "companyId") and
  -- "activeMakeMethods" is per company, so matching on the item id alone could
  -- read another tenant's row. Pre-existing in the definition this replaces.
  SELECT "readableIdWithRevision", "itemTrackingType"
    INTO v_item_readable_id, v_item_tracking_type
  FROM "item"
  WHERE "id" = p_new->>'itemId'
    AND "companyId" = p_new->>'companyId';

  SELECT "version" INTO v_version FROM "activeMakeMethods"
  WHERE "itemId" = p_new->>'itemId'
    AND "companyId" = p_new->>'companyId';

  IF NOT EXISTS (
    SELECT 1 FROM "jobMakeMethod"
    WHERE "jobId" = p_new->>'jobId' AND "parentMaterialId" = p_new->>'id'
  ) THEN
    INSERT INTO "jobMakeMethod" (
      "jobId", "parentMaterialId", "itemId", "companyId", "createdBy",
      "requiresSerialTracking", "requiresBatchTracking", "version"
    ) VALUES (
      p_new->>'jobId', p_new->>'id', p_new->>'itemId', p_new->>'companyId', p_new->>'createdBy',
      v_item_tracking_type = 'Serial', v_item_tracking_type = 'Batch', v_version
    )
    RETURNING "id" INTO v_job_make_method_id;

    INSERT INTO "trackedEntity" (
      "sourceDocument", "sourceDocumentId", "sourceDocumentReadableId",
      "quantity", "status", "companyId", "createdBy", "attributes", "itemId"
    ) VALUES (
      'Item', p_new->>'itemId', v_item_readable_id,
      (p_new->>'quantity')::numeric, 'Reserved',
      p_new->>'companyId', p_new->>'createdBy',
      jsonb_build_object('Job', p_new->>'jobId', 'Job Make Method', v_job_make_method_id, 'Job Material', p_new->>'id'),
      p_new->>'itemId'
    );
  ELSE
    UPDATE "jobMakeMethod"
    SET "itemId" = p_new->>'itemId',
        "requiresSerialTracking" = (v_item_tracking_type = 'Serial'),
        "requiresBatchTracking" = (v_item_tracking_type = 'Batch'),
        "version" = v_version
    WHERE "jobId" = p_new->>'jobId' AND "parentMaterialId" = p_new->>'id'
    RETURNING "id" INTO v_job_make_method_id;

    v_attributes := jsonb_build_object(
      'Job', p_new->>'jobId',
      'Job Make Method', v_job_make_method_id,
      'Job Material', p_new->>'id'
    );

    -- Repoint what is already there. Restricted to 'Reserved': an entity that
    -- has been consumed or received is history, and rewriting its item would
    -- falsify what was actually built.
    UPDATE "trackedEntity"
    SET "sourceDocumentId" = p_new->>'itemId',
        "sourceDocumentReadableId" = v_item_readable_id,
        "itemId" = p_new->>'itemId',
        "quantity" = (p_new->>'quantity')::numeric,
        -- Merge, don't replace: the shelf-life stamp writes expirationDate into
        -- this same attributes object, and an assignment would silently drop it.
        "attributes" = "attributes" || v_attributes
    WHERE "companyId" = p_new->>'companyId'
      AND "status" = 'Reserved'
      AND "attributes"->>'Job Material' = p_new->>'id';

    -- Only when there was nothing to repoint.
    IF NOT FOUND THEN
      INSERT INTO "trackedEntity" (
        "sourceDocument", "sourceDocumentId", "sourceDocumentReadableId",
        "quantity", "status", "companyId", "createdBy", "attributes", "itemId"
      ) VALUES (
        'Item', p_new->>'itemId', v_item_readable_id,
        (p_new->>'quantity')::numeric, 'Reserved',
        p_new->>'companyId', p_new->>'createdBy',
        v_attributes,
        p_new->>'itemId'
      );
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_job_operation_quantities(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_job_operation_id TEXT;
  v_job_id TEXT;
  v_user_id TEXT;
  v_is_last_top_level_operation BOOLEAN := FALSE;
BEGIN
  v_user_id := COALESCE(
    p_new->>'updatedBy', p_new->>'createdBy',
    p_old->>'updatedBy', p_old->>'createdBy'
  );

  IF p_operation = 'INSERT' THEN
    v_job_operation_id := p_new->>'jobOperationId';

    UPDATE "jobOperation"
    SET
      "quantityComplete" = "quantityComplete" +
        CASE WHEN (p_new->>'type') = 'Production' THEN (p_new->>'quantity')::numeric ELSE 0 END,
      "quantityReworked" = "quantityReworked" +
        CASE WHEN (p_new->>'type') = 'Rework' THEN (p_new->>'quantity')::numeric ELSE 0 END,
      "quantityScrapped" = "quantityScrapped" +
        CASE WHEN (p_new->>'type') = 'Scrap' THEN (p_new->>'quantity')::numeric ELSE 0 END
    WHERE id = v_job_operation_id;

  ELSIF p_operation = 'UPDATE' THEN
    v_job_operation_id := p_new->>'jobOperationId';

    UPDATE "jobOperation"
    SET
      "quantityComplete" = "quantityComplete"
        - CASE WHEN (p_old->>'type') = 'Production' THEN (p_old->>'quantity')::numeric ELSE 0 END
        + CASE WHEN (p_new->>'type') = 'Production' THEN (p_new->>'quantity')::numeric ELSE 0 END,
      "quantityReworked" = "quantityReworked"
        - CASE WHEN (p_old->>'type') = 'Rework' THEN (p_old->>'quantity')::numeric ELSE 0 END
        + CASE WHEN (p_new->>'type') = 'Rework' THEN (p_new->>'quantity')::numeric ELSE 0 END,
      "quantityScrapped" = "quantityScrapped"
        - CASE WHEN (p_old->>'type') = 'Scrap' THEN (p_old->>'quantity')::numeric ELSE 0 END
        + CASE WHEN (p_new->>'type') = 'Scrap' THEN (p_new->>'quantity')::numeric ELSE 0 END
    WHERE id = v_job_operation_id;

  ELSIF p_operation = 'DELETE' THEN
    v_job_operation_id := p_old->>'jobOperationId';

    UPDATE "jobOperation"
    SET
      "quantityComplete" = "quantityComplete" -
        CASE WHEN (p_old->>'type') = 'Production' THEN (p_old->>'quantity')::numeric ELSE 0 END,
      "quantityReworked" = "quantityReworked" -
        CASE WHEN (p_old->>'type') = 'Rework' THEN (p_old->>'quantity')::numeric ELSE 0 END,
      "quantityScrapped" = "quantityScrapped" -
        CASE WHEN (p_old->>'type') = 'Scrap' THEN (p_old->>'quantity')::numeric ELSE 0 END
    WHERE id = v_job_operation_id;
  END IF;

  UPDATE "jobOperation"
  SET "status" = 'Done',
      "updatedBy" = COALESCE(v_user_id, "updatedBy", "createdBy"),
      "updatedAt" = NOW()
  WHERE id = v_job_operation_id
    AND "status" NOT IN ('Done', 'Canceled')
    AND "targetQuantity" > 0
    AND ("quantityComplete" + "quantityReworked") >= "targetQuantity";

  SELECT jo."jobId" INTO v_job_id
  FROM "jobOperation" jo
  WHERE jo.id = v_job_operation_id;

  SELECT EXISTS (
    SELECT 1
    FROM "jobOperation" jo
    INNER JOIN "jobMakeMethod" jmm ON jmm.id = jo."jobMakeMethodId"
    WHERE jo.id = v_job_operation_id
      AND jmm."parentMaterialId" IS NULL
      AND NOT EXISTS (
        SELECT 1
        FROM "jobOperationDependency" dep
        INNER JOIN "jobOperation" child_jo ON child_jo.id = dep."operationId"
        INNER JOIN "jobMakeMethod" child_jmm ON child_jmm.id = child_jo."jobMakeMethodId"
        WHERE dep."dependsOnId" = jo.id
          AND child_jmm."parentMaterialId" IS NULL
      )
  ) INTO v_is_last_top_level_operation;

  IF v_job_id IS NOT NULL AND v_is_last_top_level_operation THEN
    UPDATE "job"
    SET "quantityComplete" = (
      SELECT COALESCE(SUM(terminal_jo."quantityComplete"), 0)
      FROM "jobOperation" terminal_jo
      INNER JOIN "jobMakeMethod" terminal_jmm ON terminal_jmm.id = terminal_jo."jobMakeMethodId"
      WHERE terminal_jo."jobId" = v_job_id
        AND terminal_jmm."parentMaterialId" IS NULL
        AND NOT EXISTS (
          SELECT 1
          FROM "jobOperationDependency" dep
          INNER JOIN "jobOperation" child_jo ON child_jo.id = dep."operationId"
          INNER JOIN "jobMakeMethod" child_jmm ON child_jmm.id = child_jo."jobMakeMethodId"
          WHERE dep."dependsOnId" = terminal_jo.id
            AND child_jmm."parentMaterialId" IS NULL
        )
    )
    WHERE id = v_job_id
      AND status NOT IN ('Completed', 'Cancelled');
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_quote_exchange_rate(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation = 'UPDATE'
    AND (p_old->>'exchangeRate') IS DISTINCT FROM (p_new->>'exchangeRate')
  THEN
    UPDATE "quoteLinePrice"
    SET "exchangeRate" = (p_new->>'exchangeRate')::numeric
    WHERE "quoteId" = p_new->>'id';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_quote_line_make_method_item_id(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_version NUMERIC(10, 2);
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  -- Only fire when methodType/itemId change is relevant to Make to Order
  IF NOT (
    ((p_old->>'methodType') = 'Make to Order' AND (p_old->>'itemId') IS DISTINCT FROM (p_new->>'itemId'))
    OR ((p_new->>'methodType') = 'Make to Order' AND (p_old->>'methodType') != 'Make to Order')
  ) THEN
    RETURN;
  END IF;

  SELECT "version" INTO v_version FROM "activeMakeMethods" WHERE "itemId" = p_new->>'itemId';

  IF NOT EXISTS (
    SELECT 1 FROM "quoteMakeMethod"
    WHERE "quoteLineId" = p_new->>'id' AND "parentMaterialId" IS NULL
  ) THEN
    INSERT INTO "quoteMakeMethod" (
      "quoteId", "quoteLineId", "itemId", "companyId", "createdAt", "createdBy", "version"
    ) VALUES (
      p_new->>'quoteId', p_new->>'id', p_new->>'itemId',
      p_new->>'companyId', NOW(), p_new->>'createdBy', v_version
    );
  ELSE
    UPDATE "quoteMakeMethod"
    SET "itemId" = p_new->>'itemId',
        "version" = v_version
    WHERE "quoteLineId" = p_new->>'id' AND "parentMaterialId" IS NULL;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_quote_material_make_method_item_id(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  v_version NUMERIC(10, 2);
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  IF NOT (
    ((p_old->>'methodType') = 'Make to Order' AND (p_old->>'itemId') IS DISTINCT FROM (p_new->>'itemId'))
    OR ((p_new->>'methodType') = 'Make to Order' AND (p_old->>'methodType') != 'Make to Order')
  ) THEN
    RETURN;
  END IF;

  SELECT "version" INTO v_version FROM "activeMakeMethods" WHERE "itemId" = p_new->>'itemId';

  IF NOT EXISTS (
    SELECT 1 FROM "quoteMakeMethod"
    WHERE "quoteLineId" = p_new->>'quoteLineId' AND "parentMaterialId" = p_new->>'id'
  ) THEN
    INSERT INTO "quoteMakeMethod" (
      "quoteId", "quoteLineId", "parentMaterialId", "itemId", "companyId", "createdAt", "createdBy", "version"
    ) VALUES (
      p_new->>'quoteId', p_new->>'quoteLineId', p_new->>'id', p_new->>'itemId',
      p_new->>'companyId', NOW(), p_new->>'createdBy', v_version
    );
  ELSE
    UPDATE "quoteMakeMethod"
    SET "itemId" = p_new->>'itemId',
        "version" = v_version
    WHERE "quoteLineId" = p_new->>'quoteLineId' AND "parentMaterialId" = p_new->>'id';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_sales_order_exchange_rate(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation = 'UPDATE'
    AND (p_old->>'exchangeRate') IS DISTINCT FROM (p_new->>'exchangeRate')
  THEN
    UPDATE "salesOrderLine"
    SET "exchangeRate" = (p_new->>'exchangeRate')::numeric
    WHERE "salesOrderId" = p_new->>'id';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_stock_transfer_status(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF NOT ((p_old->>'pickedQuantity') IS DISTINCT FROM (p_new->>'pickedQuantity')
          AND (p_new->>'pickedQuantity')::numeric != 0) THEN
    RETURN;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "stockTransferLine"
    WHERE "stockTransferId" = p_new->>'stockTransferId'
      AND ("pickedQuantity" IS NULL OR "pickedQuantity" != "quantity")
  ) THEN
    UPDATE "stockTransfer"
    SET "status" = 'In Progress'
    WHERE "id" = p_new->>'stockTransferId';
  ELSE
    UPDATE "stockTransfer"
    SET "status" = 'Completed', "completedAt" = NOW()
    WHERE "id" = p_new->>'stockTransferId';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_supplier_type_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  IF p_old->>'supplierTypeId' IS NOT NULL THEN
    IF p_new->>'supplierTypeId' IS NOT NULL THEN
      UPDATE "membership" SET "groupId" = p_new->>'supplierTypeId'
      WHERE "groupId" = p_old->>'supplierTypeId' AND "memberGroupId" = p_new->>'id';
    ELSE
      DELETE FROM "membership"
      WHERE "groupId" = p_old->>'supplierTypeId' AND "memberGroupId" = p_new->>'id';
    END IF;
  ELSE
    IF p_new->>'supplierTypeId' IS NOT NULL THEN
      INSERT INTO "membership" ("groupId", "memberGroupId")
      VALUES (p_new->>'supplierTypeId', p_new->>'id');
    END IF;
  END IF;

  UPDATE "group" SET "name" = p_new->>'name'
  WHERE "id" = p_new->>'id' AND "isSupplierOrgGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_supplier_type_group_name(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  UPDATE "group"
  SET "name" = p_new->>'name'
  WHERE "id" = p_new->>'id'
    AND "isSupplierTypeGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_tracked_entity_on_job_make_method(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;
  IF (p_old->>'id') IS NOT DISTINCT FROM (p_new->>'id') THEN RETURN; END IF;

  UPDATE "trackedEntity"
  SET "attributes" = jsonb_set(
    "attributes",
    '{Job Make Method}',
    to_jsonb(p_new->>'id')
  )
  WHERE "attributes"->>'Job Make Method' = p_old->>'id';
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_update_user_identity_group(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_operation != 'UPDATE' THEN RETURN; END IF;

  UPDATE "group"
  SET "name" = p_new->>'fullName'
  WHERE "id" = p_new->>'id'
    AND "isIdentityGroup" = TRUE;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_upload_document_transaction(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF p_operation != 'INSERT' THEN RETURN; END IF;

  INSERT INTO "documentTransaction" ("documentId", "type", "userId")
  VALUES (p_new->>'id', 'Upload', p_new->>'createdBy');
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_verify_integration(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  integration_schema JSON;
BEGIN
  IF p_operation NOT IN ('INSERT', 'UPDATE') THEN RETURN; END IF;

  SELECT jsonschema INTO integration_schema
  FROM public.integration
  WHERE id = p_new->>'id';

  IF (p_new->>'active')::boolean = TRUE
     AND NOT extensions.json_matches_schema(integration_schema, (p_new->'metadata')::json) THEN
    RAISE EXCEPTION 'metadata does not match jsonschema';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.sync_webhook_subscription(p_table text, p_operation text, p_new jsonb, p_old jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
DECLARE
  v_ops TEXT[];
  v_name TEXT;
BEGIN
  IF p_operation = 'DELETE' THEN
    PERFORM delete_event_system_subscriptions_by_name(
      p_old->>'companyId', 'webhook-' || (p_old->>'id')
    );
    RETURN;
  END IF;

  v_name := 'webhook-' || (p_new->>'id');

  -- Clear first: `table` is editable and uniqueness is (companyId, name, table),
  -- so an upsert would strand the old row and fire the webhook twice.
  PERFORM delete_event_system_subscriptions_by_name(p_new->>'companyId', v_name);

  v_ops := ARRAY[]::TEXT[];
  IF (p_new->>'onInsert')::BOOLEAN THEN v_ops := array_append(v_ops, 'INSERT'); END IF;
  IF (p_new->>'onUpdate')::BOOLEAN THEN v_ops := array_append(v_ops, 'UPDATE'); END IF;
  IF (p_new->>'onDelete')::BOOLEAN THEN v_ops := array_append(v_ops, 'DELETE'); END IF;

  IF array_length(v_ops, 1) IS NULL THEN
    RETURN;
  END IF;

  PERFORM create_event_system_subscription(
    v_name,
    p_new->>'table',
    p_new->>'companyId',
    v_ops,
    'WEBHOOK',
    jsonb_build_object('url', p_new->>'url', 'webhookId', p_new->>'id'),
    '{}'::jsonb,
    COALESCE((p_new->>'active')::BOOLEAN, false)
  );
END;
$function$;

-- event triggers (packages/database/src/event-system/attachments.ts)
SET lock_timeout = '5s';
SELECT set_event_triggers('ability', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('address', ARRAY['sync_address_to_parent']::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('assemblyPlanJob', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('changeOrder', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('charge', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('company', ARRAY[]::text[], ARRAY['sync_insert_company_related_records']::text[], false, ARRAY[]::text[]);
SELECT set_event_triggers('companyIntegration', ARRAY['sync_verify_integration']::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('contact', ARRAY['sync_contact_to_parent']::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customField', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('customer', ARRAY['sync_update_customer_type_group']::text[], ARRAY['sync_create_customer_entries', 'sync_create_customer_org_group']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('customerAccount', ARRAY[]::text[], ARRAY['sync_add_customer_account_to_group']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerContact', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('customerItemPriceOverride', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerItemPriceOverrideBreak', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerLocation', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('customerPartToItem', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerPayment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerShipping', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerTax', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('customerType', ARRAY['sync_update_customer_type_group_name']::text[], ARRAY['sync_create_customer_type_group']::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('document', ARRAY['sync_edit_document_transaction']::text[], ARRAY['sync_upload_document_transaction']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('documentExtraction', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('documentTemplate', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('employee', ARRAY['sync_update_employee_type_membership']::text[], ARRAY['sync_add_employee_to_type_group']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('employeeJob', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('employeeType', ARRAY['sync_update_employee_type_group']::text[], ARRAY['sync_create_employee_type_group']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('fixedAsset', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('gauge', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('gaugeCalibrationRecord', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('implementationCheckState', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('implementationFieldValue', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('implementationHub', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('implementationRow', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('inspection', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('inventoryCount', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('inventoryCountLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('invite', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('itarCertification', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('item', ARRAY[]::text[], ARRAY['sync_create_item_related_records', 'sync_create_make_method_related_records', 'sync_propagate_item_readable_id_to_tracked_entity']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('itemCost', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('itemLedger', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['apply_item_stock_quantities', 'broadcast_table_changes']::text[]);
SELECT set_event_triggers('itemPlanning', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('itemPostingGroup', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('itemReplenishment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('itemShelfLife', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('itemStockQuantities', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('itemSupersession', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('itemUnitSalePrice', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('job', ARRAY['sync_job_complete_or_canceled']::text[], ARRAY['sync_insert_job_make_method', 'sync_job_recompute_service_line']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('jobMakeMethod', ARRAY['sync_update_tracked_entity_on_job_make_method', 'sync_delete_tracked_entity_on_job_make_method']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('jobMaterial', ARRAY['sync_check_job_material_self_reference', 'sync_update_job_material_make_method_item_id']::text[], ARRAY['sync_insert_job_material_make_method']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('jobOperation', ARRAY['sync_finish_job_operation']::text[], ARRAY['set_shelf_life_on_operation_done', 'set_shelf_life_on_operation_started']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('jobOperationDependency', ARRAY[]::text[], ARRAY['sync_set_initial_dependency_status']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('jobOperationNote', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('jobOperationStep', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('jobOperationStepRecord', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('journal', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('location', ARRAY[]::text[], ARRAY['sync_create_location_related_records']::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('maintenanceDispatch', ARRAY[]::text[], ARRAY['sync_on_maintenance_dispatch_complete']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('maintenanceDispatchComment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('maintenanceDispatchEvent', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('maintenanceSchedule', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('maintenanceScheduleItem', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('material', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('materialForm', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('materialSubstance', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('materialType', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('methodMaterial', ARRAY['sync_check_method_material_self_reference']::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('modelUpload', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('nonConformance', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('nonConformanceActionTask', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('nonConformanceApprovalTask', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('nonConformanceItem', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('nonConformanceRequiredAction', ARRAY['sync_protect_system_required_actions']::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('nonConformanceSupplier', ARRAY[]::text[], ARRAY['sync_create_nc_external_link']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('nonConformanceType', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('notification', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_user_changes']::text[]);
SELECT set_event_triggers('part', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('payment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('paymentTerm', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('pickingList', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('pickingListLine', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('printJob', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('procedure', ARRAY['sync_archive_other_procedures']::text[], ARRAY[]::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('process', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('productionEvent', ARRAY['sync_set_job_operation_in_progress']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('productionQuantity', ARRAY['sync_update_job_operation_quantities']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseInvoice', ARRAY['prevent_posted_purchase_invoice_deletion']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseInvoiceLine', ARRAY[]::text[], ARRAY['sync_purchase_invoice_line_price_change']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseOrder', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseOrderDelivery', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('purchaseOrderLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseOrderPayment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('purchaseReturnOrder', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchasingRfq', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('qualityDocument', ARRAY['sync_archive_other_quality_documents']::text[], ARRAY[]::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('quote', ARRAY['sync_update_quote_exchange_rate']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('quoteLine', ARRAY['sync_update_quote_line_make_method_item_id']::text[], ARRAY['sync_insert_quote_line_make_method']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('quoteMaterial', ARRAY['sync_update_quote_material_make_method_item_id']::text[], ARRAY['sync_insert_quote_material_make_method']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('quoteOperation', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('receipt', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('receiptLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('reimbursement', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('salesInvoice', ARRAY['prevent_posted_sales_invoice_deletion']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesInvoiceLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesInvoiceShipment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('salesOrder', ARRAY['sync_update_sales_order_exchange_rate']::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesOrderLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesOrderPayment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('salesOrderShipment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('salesReturnOrder', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesRfq', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesRfqLine', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('shipment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('shipmentLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('shippingMethod', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('stockTransfer', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('stockTransferLine', ARRAY[]::text[], ARRAY['sync_update_stock_transfer_status']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('storageUnit', ARRAY['storage_unit_enforce_same_location', 'storage_unit_block_location_change_with_children', 'storage_unit_enforce_no_cycle']::text[], ARRAY[]::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('supplier', ARRAY['sync_update_supplier_type_group']::text[], ARRAY['sync_create_supplier_entries', 'sync_create_supplier_org_group']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('supplierAccount', ARRAY[]::text[], ARRAY['sync_add_supplier_account_to_group']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('supplierContact', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('supplierLocation', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('supplierPart', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('supplierPayment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('supplierProcess', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('supplierQuote', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('supplierQuoteLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('supplierShipping', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('supplierTax', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('supplierType', ARRAY['sync_update_supplier_type_group_name']::text[], ARRAY['sync_create_supplier_type_group']::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('trackedEntity', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('unitOfMeasure', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('user', ARRAY[]::text[], ARRAY['sync_create_user_identity_group', 'sync_update_user_identity_group', 'sync_delete_user_identity_group']::text[], false, ARRAY[]::text[]);
SELECT set_event_triggers('warehouseTransfer', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('warehouseTransferLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('webhook', ARRAY[]::text[], ARRAY['sync_webhook_subscription']::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('workCenter', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_reference_changes']::text[]);
SELECT set_event_triggers('workCenterProcess', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY[]::text[]);
SELECT set_event_triggers('workflowRun', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('workflowStepRun', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
RESET lock_timeout;
