-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- demandActual
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'demandActual' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'demandActual');
  END LOOP;
END
$authz$;
ALTER TABLE public."demandActual" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."demandActual" FOR SELECT USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) OR "companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_view'))::text[])));
CREATE POLICY "INSERT" ON "public"."demandActual" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."demandActual" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."demandActual" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- demandForecast
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'demandForecast' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'demandForecast');
  END LOOP;
END
$authz$;
ALTER TABLE public."demandForecast" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."demandForecast" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."demandForecast" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."demandForecast" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."demandForecast" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- demandForecastSource
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'demandForecastSource' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'demandForecastSource');
  END LOOP;
END
$authz$;
ALTER TABLE public."demandForecastSource" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."demandForecastSource" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."demandForecastSource" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."demandForecastSource" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."demandForecastSource" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- demandProjection
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'demandProjection' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'demandProjection');
  END LOOP;
END
$authz$;
ALTER TABLE public."demandProjection" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."demandProjection" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."demandProjection" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."demandProjection" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."demandProjection" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- document
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'document' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'document');
  END LOOP;
END
$authz$;
ALTER TABLE public."document" ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "DELETE" ON "public"."document" AS PERMISSIVE FOR DELETE TO public USING ((("companyId" = ANY (( SELECT get_companies_with_employee_permission('documents_delete'::text) AS get_companies_with_employee_permission)::text[])) AND (has_valid_api_key_for_company("companyId") OR ((groups_for_user((( SELECT auth.uid() AS uid))::text) && "writeGroups") = true))));
    CREATE POLICY "INSERT" ON "public"."document" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((("companyId" = ANY (( SELECT get_companies_with_employee_permission('documents_create'::text) AS get_companies_with_employee_permission)::text[])) AND (has_valid_api_key_for_company("companyId") OR ((groups_for_user((( SELECT auth.uid() AS uid))::text) && "writeGroups") = true))));
    CREATE POLICY "SELECT" ON "public"."document" AS PERMISSIVE FOR SELECT TO public USING ((("companyId" = ANY (( SELECT get_companies_with_employee_permission('documents_view'::text) AS get_companies_with_employee_permission)::text[])) AND (has_valid_api_key_for_company("companyId") OR ((groups_for_user((( SELECT auth.uid() AS uid))::text) && "readGroups") = true))));
    CREATE POLICY "UPDATE" ON "public"."document" AS PERMISSIVE FOR UPDATE TO public USING ((("companyId" = ANY (( SELECT get_companies_with_employee_permission('documents_update'::text) AS get_companies_with_employee_permission)::text[])) AND (has_valid_api_key_for_company("companyId") OR ((groups_for_user((( SELECT auth.uid() AS uid))::text) && "writeGroups") = true))));
  

-- supplyActual
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'supplyActual' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'supplyActual');
  END LOOP;
END
$authz$;
ALTER TABLE public."supplyActual" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."supplyActual" FOR SELECT USING (("companyId" = ANY ((SELECT get_companies_with_employee_permission('parts_view'))::text[]) OR "companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_view'))::text[])));
CREATE POLICY "INSERT" ON "public"."supplyActual" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."supplyActual" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."supplyActual" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- supplyForecast
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'supplyForecast' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'supplyForecast');
  END LOOP;
END
$authz$;
ALTER TABLE public."supplyForecast" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."supplyForecast" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."supplyForecast" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."supplyForecast" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."supplyForecast" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('inventory_delete'))::text[]));

-- userAttribute
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userAttribute' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userAttribute');
  END LOOP;
END
$authz$;
ALTER TABLE public."userAttribute" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userAttribute" FOR SELECT USING ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_view'))::text[])));
CREATE POLICY "INSERT" ON "public"."userAttribute" FOR INSERT WITH CHECK ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."userAttribute" FOR UPDATE USING ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."userAttribute" FOR DELETE USING ("userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_delete'))::text[])));

-- userAttributeCategory
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userAttributeCategory' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userAttributeCategory');
  END LOOP;
END
$authz$;
ALTER TABLE public."userAttributeCategory" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userAttributeCategory" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_view'))::text[]));
CREATE POLICY "INSERT" ON "public"."userAttributeCategory" FOR INSERT WITH CHECK ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_create'))::text[]));
CREATE POLICY "UPDATE" ON "public"."userAttributeCategory" FOR UPDATE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[]));
CREATE POLICY "DELETE" ON "public"."userAttributeCategory" FOR DELETE USING ("companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_delete'))::text[]));

-- userAttributeValue
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'userAttributeValue' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'userAttributeValue');
  END LOOP;
END
$authz$;
ALTER TABLE public."userAttributeValue" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."userAttributeValue" FOR SELECT USING ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
CREATE POLICY "INSERT" ON "public"."userAttributeValue" FOR INSERT WITH CHECK ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
CREATE POLICY "UPDATE" ON "public"."userAttributeValue" FOR UPDATE USING ((("userId" = ((SELECT auth.uid()))::text AND "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE ("canSelfManage" = true AND "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text))))) OR "userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[])))));
CREATE POLICY "DELETE" ON "public"."userAttributeValue" FOR DELETE USING ("userAttributeId" IN (SELECT "userAttribute"."id" FROM "public"."userAttribute" WHERE "userAttributeCategoryId" IN (SELECT "userAttributeCategory"."id" FROM "public"."userAttributeCategory" WHERE "companyId" = ANY ((SELECT get_companies_with_employee_permission('resources_update'))::text[]))));
