-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- event triggers (packages/database/src/event-system/attachments.ts)
SET lock_timeout = '5s';
SELECT set_event_triggers('inspectionSample', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('inventoryCountLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('nonConformanceItem', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('payment', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchaseReturnOrderLine', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('purchasingRfqLine', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('quoteMakeMethod', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('salesReturnOrderLine', ARRAY[]::text[], ARRAY[]::text[], false, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('stockTransferLine', ARRAY[]::text[], ARRAY['sync_update_stock_transfer_status']::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('supplierQuoteLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
SELECT set_event_triggers('warehouseTransferLine', ARRAY[]::text[], ARRAY[]::text[], true, ARRAY['broadcast_table_changes']::text[]);
RESET lock_timeout;
