-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- charge
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'charge' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'charge');
  END LOOP;
END
$authz$;
ALTER TABLE public."charge" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."charge" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."charge" FOR INSERT WITH CHECK (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."charge" FOR UPDATE USING (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."charge" FOR DELETE USING (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_delete'))::text[])));

-- chargeLine
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'chargeLine' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'chargeLine');
  END LOOP;
END
$authz$;
ALTER TABLE public."chargeLine" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."chargeLine" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."chargeLine" FOR INSERT WITH CHECK ((EXISTS (SELECT 1 FROM "public"."charge" p WHERE "p"."id" = "chargeLine"."chargeId" AND "p"."companyId" = "chargeLine"."companyId" AND "status" = 'Draft') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."chargeLine" FOR UPDATE USING ((EXISTS (SELECT 1 FROM "public"."charge" p WHERE "p"."id" = "chargeLine"."chargeId" AND "p"."companyId" = "chargeLine"."companyId" AND "status" = 'Draft') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."chargeLine" FOR DELETE USING ((EXISTS (SELECT 1 FROM "public"."charge" p WHERE "p"."id" = "chargeLine"."chargeId" AND "p"."companyId" = "chargeLine"."companyId" AND "status" = 'Draft') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_delete'))::text[])));

-- reimbursement
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reimbursement' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'reimbursement');
  END LOOP;
END
$authz$;
ALTER TABLE public."reimbursement" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."reimbursement" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."reimbursement" FOR INSERT WITH CHECK (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."reimbursement" FOR UPDATE USING (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."reimbursement" FOR DELETE USING (("status" = 'Draft' AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_delete'))::text[])));

-- reimbursementLine
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reimbursementLine' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'reimbursementLine');
  END LOOP;
END
$authz$;
ALTER TABLE public."reimbursementLine" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."reimbursementLine" FOR SELECT USING ("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]));
CREATE POLICY "INSERT" ON "public"."reimbursementLine" FOR INSERT WITH CHECK ((EXISTS (SELECT 1 FROM "public"."reimbursement" p WHERE "p"."id" = "reimbursementLine"."reimbursementId" AND "p"."companyId" = "reimbursementLine"."companyId" AND "status" = 'Draft') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_create'))::text[])));
CREATE POLICY "UPDATE" ON "public"."reimbursementLine" FOR UPDATE USING ((EXISTS (SELECT 1 FROM "public"."reimbursement" p WHERE "p"."id" = "reimbursementLine"."reimbursementId" AND "p"."companyId" = "reimbursementLine"."companyId" AND "status" = 'Draft') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_update'))::text[])));
CREATE POLICY "DELETE" ON "public"."reimbursementLine" FOR DELETE USING ((EXISTS (SELECT 1 FROM "public"."reimbursement" p WHERE "p"."id" = "reimbursementLine"."reimbursementId" AND "p"."companyId" = "reimbursementLine"."companyId" AND "status" = 'Draft') AND "companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_delete'))::text[])));

-- reimbursementLineDimension
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'reimbursementLineDimension' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'reimbursementLineDimension');
  END LOOP;
END
$authz$;
ALTER TABLE public."reimbursementLineDimension" ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "SELECT" ON "public"."reimbursementLineDimension" AS PERMISSIVE FOR SELECT TO public USING (("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
    CREATE POLICY "INSERT" ON "public"."reimbursementLineDimension" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS (SELECT 1 FROM public."reimbursementLine" l JOIN public."reimbursement" h ON ((h.id = l."reimbursementId") AND (h."companyId" = l."companyId")) WHERE ((l.id = "public"."reimbursementLineDimension"."reimbursementLineId") AND (l."companyId" = "public"."reimbursementLineDimension"."companyId") AND (h.status = 'Draft'::"reimbursementStatus"))) AND ("companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_create'::text))::text[]))));
    CREATE POLICY "DELETE" ON "public"."reimbursementLineDimension" AS PERMISSIVE FOR DELETE TO public USING ((EXISTS (SELECT 1 FROM public."reimbursementLine" l JOIN public."reimbursement" h ON ((h.id = l."reimbursementId") AND (h."companyId" = l."companyId")) WHERE ((l.id = "public"."reimbursementLineDimension"."reimbursementLineId") AND (l."companyId" = "public"."reimbursementLineDimension"."companyId") AND (h.status = 'Draft'::"reimbursementStatus"))) AND ("companyId" = ANY ((SELECT get_companies_with_employee_permission('invoicing_delete'::text))::text[]))));
  
