-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

CREATE OR REPLACE FUNCTION util.sweep_embedding_queue()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pgmq', 'extensions'
AS $function$
BEGIN
  -- Only visible messages count: rows hidden by a read's visibility timeout
  -- are already being drained.
  IF EXISTS (
    SELECT 1 FROM pgmq.q_embedding_jobs WHERE vt <= clock_timestamp()
  ) THEN
    PERFORM util.send_inngest_event('carbon/embedding-queue.process', '{}'::jsonb);
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION util.wake_event_queue()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  PERFORM util.send_inngest_event('carbon/event-queue.process', '{}'::jsonb);
END;
$function$;
