-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- changelogDispatch
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'changelogDispatch' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'changelogDispatch');
  END LOOP;
END
$authz$;
ALTER TABLE public."changelogDispatch" ENABLE ROW LEVEL SECURITY;
