-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.

-- Ships these rules to databases where `authz sync` does not run after migrations yet.

-- agentMessagePart
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'agentMessagePart' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'agentMessagePart');
  END LOOP;
END
$authz$;
ALTER TABLE public."agentMessagePart" ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "INSERT" ON "public"."agentMessagePart" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((("companyId" = ANY (( SELECT get_companies_with_employee_role() AS get_companies_with_employee_role)::text[])) AND (EXISTS ( SELECT 1
   FROM ("agentMessage" m
     JOIN "agentThread" t ON (((t.id = m."threadId") AND (t."companyId" = m."companyId"))))
  WHERE ((m.id = "agentMessagePart"."messageId") AND (m."companyId" = "agentMessagePart"."companyId") AND (t."userId" = (( SELECT auth.uid() AS uid))::text))))));
    CREATE POLICY "SELECT" ON "public"."agentMessagePart" AS PERMISSIVE FOR SELECT TO public USING ((("companyId" = ANY (( SELECT get_companies_with_employee_role() AS get_companies_with_employee_role)::text[])) AND (EXISTS ( SELECT 1
   FROM ("agentMessage" m
     JOIN "agentThread" t ON (((t.id = m."threadId") AND (t."companyId" = m."companyId"))))
  WHERE ((m.id = "agentMessagePart"."messageId") AND (m."companyId" = "agentMessagePart"."companyId") AND (t."userId" = (( SELECT auth.uid() AS uid))::text))))));
    CREATE POLICY "UPDATE" ON "public"."agentMessagePart" AS PERMISSIVE FOR UPDATE TO public USING ((("companyId" = ANY (( SELECT get_companies_with_employee_role() AS get_companies_with_employee_role)::text[])) AND (EXISTS ( SELECT 1
   FROM ("agentMessage" m
     JOIN "agentThread" t ON (((t.id = m."threadId") AND (t."companyId" = m."companyId"))))
  WHERE ((m.id = "agentMessagePart"."messageId") AND (m."companyId" = "agentMessagePart"."companyId") AND (t."userId" = (( SELECT auth.uid() AS uid))::text))))));
  

-- companyGroup
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'companyGroup' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'companyGroup');
  END LOOP;
END
$authz$;
ALTER TABLE public."companyGroup" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."companyGroup" FOR SELECT USING ("id" IN (SELECT "company"."companyGroupId" FROM "public"."company" WHERE "id" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));

-- notificationDelivery
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'notificationDelivery' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'notificationDelivery');
  END LOOP;
END
$authz$;
ALTER TABLE public."notificationDelivery" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."notificationDelivery" FOR SELECT USING ("userId" = ((SELECT auth.uid()))::text);

-- notificationPreference
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'notificationPreference' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'notificationPreference');
  END LOOP;
END
$authz$;
ALTER TABLE public."notificationPreference" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."notificationPreference" FOR SELECT USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "INSERT" ON "public"."notificationPreference" FOR INSERT WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "UPDATE" ON "public"."notificationPreference" FOR UPDATE USING ("userId" = ((SELECT auth.uid()))::text) WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "DELETE" ON "public"."notificationPreference" FOR DELETE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" IN (SELECT "userToCompany"."companyId" FROM "public"."userToCompany" WHERE "userId" = ((SELECT auth.uid()))::text)));

-- agentThread
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'agentThread' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'agentThread');
  END LOOP;
END
$authz$;
ALTER TABLE public."agentThread" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."agentThread" FOR SELECT USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "INSERT" ON "public"."agentThread" FOR INSERT WITH CHECK (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "UPDATE" ON "public"."agentThread" FOR UPDATE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));
CREATE POLICY "DELETE" ON "public"."agentThread" FOR DELETE USING (("userId" = ((SELECT auth.uid()))::text AND "companyId" = ANY ((SELECT get_companies_with_employee_role())::text[])));

-- agentMessage
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'agentMessage' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'agentMessage');
  END LOOP;
END
$authz$;
ALTER TABLE public."agentMessage" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."agentMessage" FOR SELECT USING (("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]) AND EXISTS (SELECT 1 FROM "public"."agentThread" p WHERE "p"."id" = "agentMessage"."threadId" AND "p"."companyId" = "agentMessage"."companyId" AND "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "INSERT" ON "public"."agentMessage" FOR INSERT WITH CHECK (("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]) AND EXISTS (SELECT 1 FROM "public"."agentThread" p WHERE "p"."id" = "agentMessage"."threadId" AND "p"."companyId" = "agentMessage"."companyId" AND "userId" = ((SELECT auth.uid()))::text)));
CREATE POLICY "UPDATE" ON "public"."agentMessage" FOR UPDATE USING (("companyId" = ANY ((SELECT get_companies_with_employee_role())::text[]) AND EXISTS (SELECT 1 FROM "public"."agentThread" p WHERE "p"."id" = "agentMessage"."threadId" AND "p"."companyId" = "agentMessage"."companyId" AND "userId" = ((SELECT auth.uid()))::text)));

-- ssoReservedDomain
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'ssoReservedDomain' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'ssoReservedDomain');
  END LOOP;
END
$authz$;
ALTER TABLE public."ssoReservedDomain" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."ssoReservedDomain" FOR SELECT USING ((SELECT auth.role()) = 'authenticated');

-- scriptRun
DO $authz$
DECLARE p record;
BEGIN
  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'scriptRun' LOOP
    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, 'scriptRun');
  END LOOP;
END
$authz$;
ALTER TABLE public."scriptRun" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "SELECT" ON "public"."scriptRun" FOR SELECT USING ((SELECT auth.role()) = 'authenticated');
