CREATE OR REPLACE FUNCTION public.create_company_search_index(p_company_id text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_table_name TEXT;
BEGIN
  v_table_name := 'searchIndex_' || p_company_id;

  -- Create the search index table
  EXECUTE format('
    CREATE TABLE IF NOT EXISTS %I (
      "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "entityType" TEXT NOT NULL,
      "entityId" TEXT NOT NULL,
      "title" TEXT NOT NULL,
      "description" TEXT DEFAULT '''',
      "link" TEXT NOT NULL,
      "tags" TEXT[] DEFAULT ''{}'',
      "metadata" JSONB DEFAULT ''{}'',
      "searchVector" TSVECTOR,
      "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      "updatedAt" TIMESTAMP WITH TIME ZONE,
      CONSTRAINT %I UNIQUE ("entityType", "entityId")
    )', v_table_name, v_table_name || '_entity_unique');

  -- GIN on searchVector: FTS path (multi-word, stemmed prefix via :*).
  EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I USING GIN ("searchVector")',
    v_table_name || '_fts_idx', v_table_name);

  -- GIN trigram on title: substring path (find "269" inside "S000269").
  EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I USING GIN ("title" gin_trgm_ops)',
    v_table_name || '_title_trgm_idx', v_table_name);

  -- GIN trigram on description: substring path for hits that live in the body text.
  EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I USING GIN ("description" gin_trgm_ops)',
    v_table_name || '_description_trgm_idx', v_table_name);

  -- Enable RLS (no SELECT policies - access via service role bypass)
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', v_table_name);

  INSERT INTO "searchIndexRegistry" ("companyId")
  VALUES (p_company_id)
  ON CONFLICT ("companyId") DO NOTHING;
END;
$function$;
