#pragma once
#include <cstdint>
#include "rust/cxx.h"

namespace carbon_occt {
struct Tree;  // generated by cxx from the shared struct

Tree read_step(rust::Str path, double linear_deflection, double angular_deflection);

bool write_test_step(rust::Str path, uint32_t boxes);
}  // namespace carbon_occt
