import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "libpg-query";
import { type Helper, RETIRED_HELPERS } from "./helpers";
import { type AnyRule, type Manifest, render } from "./rules";
import { assertOnlyPolicies } from "./sync";

/**
 * Production does not run `authz sync` yet, so a manifest or helper change reaches it only
 * through a migration rendered by `authz migration`. `unshipped()` (pinned by
 * migration.test.ts, which runs in CI with no database) fails any rule or helper that
 * no generated migration ships:
 *
 * - a table or helper in a generated migration must equal what the manifest renders now,
 *   as of the LATEST generated migration that names it;
 * - anything never shipped that way must hash to baseline.json — what production had when
 *   the manifest took over (text may differ; the meaning was proven equal). The baseline is
 *   written once and never regenerated: a change goes into a generated migration instead.
 *
 * A new table appears in neither, so it cannot reach production without its policies.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const MIGRATIONS_DIR = path.resolve(HERE, "../../supabase/migrations");
const BASELINE = path.join(HERE, "baseline.json");

/**
 * The first line of every generated authz migration. `@carbon/checks`
 * (no-authz-ddl-in-migrations) exempts the files that start with it; `unshipped()` checks
 * their contents, so the header cannot be borrowed by a hand-written file.
 */
export const GENERATED_HEADER =
  "-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.";

const literal = (s: string) => `'${s.replaceAll("'", "''")}'`;
const ident = (s: string) => `"${s.replaceAll('"', '""')}"`;
export const hash = (sql: string) =>
  createHash("sha256").update(sql).digest("hex").slice(0, 16);

const dropAllPolicies = (table: string) =>
  [
    "DO $authz$",
    "DECLARE p record;",
    "BEGIN",
    `  FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = ${literal(table)} LOOP`,
    `    EXECUTE format('DROP POLICY %I ON public.%I', p.policyname, ${literal(table)});`,
    "  END LOOP;",
    "END",
    "$authz$;"
  ].join("\n");

/**
 * Chosen helpers and tables rendered from the manifest as one migration. Each table's
 * policies are dropped whatever their names (legacy names included) and recreated from its
 * rule, so the migration lands the manifest's exact rule; `authz sync` after it changes
 * nothing.
 */
export async function renderMigration(
  manifest: Manifest,
  helpers: Helper[],
  tables: string[]
): Promise<string> {
  const parts = [
    GENERATED_HEADER,
    "-- Ships these rules to databases where `authz sync` does not run after migrations yet."
  ];

  for (const helper of helpers) parts.push(helper.sql.trim());

  for (const table of tables) {
    const rule = (manifest as Record<string, AnyRule>)[table];
    if (!rule)
      throw new Error(`authz migration: no rule for "${table}" in manifest.ts`);
    const sql = render(rule, table);
    if (sql) await assertOnlyPolicies(sql, "public", table);
    parts.push(
      [
        `-- ${table}`,
        dropAllPolicies(table),
        `ALTER TABLE public.${ident(table)} ENABLE ROW LEVEL SECURITY;`,
        sql
      ]
        .filter(Boolean)
        .join("\n")
    );
  }

  return `${parts.join("\n\n")}\n`;
}

// biome-ignore lint/suspicious/noExplicitAny: libpg-query's AST is untyped JSON
type Ast = any;

/** Each statement's AST and its own text (comments before it and the `;` excluded). */
async function statements(sql: string): Promise<{ node: Ast; text: string }[]> {
  const tree: Ast = await parse(sql);
  const bytes = Buffer.from(sql);
  return (tree.stmts ?? []).map((s: Ast) => {
    const start = s.stmt_location ?? 0;
    const end = s.stmt_len ? start + s.stmt_len : bytes.length;
    const text = bytes
      .subarray(start, end)
      .toString()
      .replace(/^(\s*--[^\n]*\n)+/, "")
      .trim();
    return { node: s.stmt, text };
  });
}

type Shipped = {
  tables: Map<string, { file: string; policies: string[] }>;
  helpers: Map<string, { file: string; text: string }>;
  problems: string[];
};

/**
 * What the generated migrations ship, latest file winning. A generated file may contain
 * only managed helpers and, per table, the drop-all block, ENABLE ROW LEVEL SECURITY and
 * policies on that table — anything else is reported.
 */
async function readShipped(dir: string, managed: Set<string>) {
  const shipped: Shipped = {
    tables: new Map(),
    helpers: new Map(),
    problems: []
  };
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  for (const file of files) {
    const sql = readFileSync(path.join(dir, file), "utf8");
    if (!sql.startsWith(GENERATED_HEADER)) continue;
    let table: string | undefined;
    for (const { node, text } of await statements(sql)) {
      const fn = node.CreateFunctionStmt;
      const alter = node.AlterTableStmt;
      const policy = node.CreatePolicyStmt?.table;
      if (fn) {
        const [schema, name] = fn.funcname.map((n: Ast) => n.String?.sval);
        if (schema === "public" && managed.has(name)) {
          shipped.helpers.set(name, { file, text });
          continue;
        }
        if (schema === "public" && RETIRED_HELPERS[name] === file) continue;
      } else if (node.DoStmt) {
        table = /tablename = '((?:[^']|'')+)'/
          .exec(text)?.[1]
          ?.replaceAll("''", "'");
        if (
          table &&
          text === (await statements(dropAllPolicies(table)))[0]?.text
        )
          continue;
      } else if (alter) {
        const cmds = alter.cmds ?? [];
        if (
          table &&
          alter.relation?.schemaname === "public" &&
          alter.relation?.relname === table &&
          cmds.length === 1 &&
          cmds[0].AlterTableCmd?.subtype === "AT_EnableRowSecurity"
        ) {
          shipped.tables.set(table, { file, policies: [] });
          continue;
        }
      } else if (
        table &&
        policy?.schemaname === "public" &&
        policy?.relname === table &&
        shipped.tables.get(table)?.file === file
      ) {
        shipped.tables.get(table)?.policies.push(text);
        continue;
      }
      shipped.problems.push(
        `${file}: not something \`authz migration\` writes: ${text.slice(0, 80)}`
      );
    }
  }
  return shipped;
}

export type Unshipped = {
  tables: string[];
  helpers: string[];
  problems: string[];
};

/** Every rule and helper production does not have yet, and any tampered generated file. */
export async function unshipped(
  manifest: Manifest,
  helpers: Helper[],
  dir = MIGRATIONS_DIR
): Promise<Unshipped> {
  const baseline: {
    tables: Record<string, string>;
    helpers: Record<string, string>;
  } = JSON.parse(readFileSync(BASELINE, "utf8"));
  const shipped = await readShipped(dir, new Set(helpers.map((h) => h.name)));
  const result: Unshipped = {
    tables: [],
    helpers: [],
    problems: shipped.problems
  };

  for (const [table, rule] of Object.entries(manifest) as [string, AnyRule][]) {
    const sql = render(rule, table);
    const got = shipped.tables.get(table);
    const same = got
      ? JSON.stringify(got.policies) ===
        JSON.stringify(sql ? (await statements(sql)).map((s) => s.text) : [])
      : baseline.tables[table] === hash(sql);
    if (!same) result.tables.push(table);
  }

  for (const helper of helpers) {
    const got = shipped.helpers.get(helper.name);
    const same = got
      ? got.text === (await statements(helper.sql))[0]?.text
      : baseline.helpers[helper.name] === hash(helper.sql);
    if (!same) result.helpers.push(helper.name);
  }

  return result;
}
