// import { error } from "@carbon/auth";
import { requirePermissions } from "@carbon/auth/auth.server";
import { isUnsafeStoragePath } from "@carbon/files";
import { trigger } from "@carbon/jobs";
import type { ActionFunctionArgs } from "react-router";
import { isAssemblerServiceHealthy } from "~/modules/production/production.server";

export async function action({ request }: ActionFunctionArgs) {
  const { client, companyId, userId } = await requirePermissions(request, {
    update: "parts"
  });

  const formData = await request.formData();
  const modelId = formData.get("modelId") as string;
  const name = formData.get("name") as string;
  const modelPath = formData.get("modelPath") as string;
  const size = parseInt(formData.get("size") as string);
  const convert = formData.get("convert") === "true";

  const itemId = formData.get("itemId") as string | null;
  const salesRfqLineId = formData.get("salesRfqLineId") as string | null;
  const quoteLineId = formData.get("quoteLineId") as string | null;
  const salesOrderLineId = formData.get("salesOrderLineId") as string | null;
  const jobId = formData.get("jobId") as string | null;

  if (!modelId) {
    throw new Error("File ID is required");
  }
  if (!name) {
    throw new Error("Name is required");
  }
  if (!modelPath) {
    throw new Error("Model path is required");
  }
  // The path is client-supplied; never let it point outside this tenant's
  // storage prefix or escape via traversal.
  if (
    !modelPath.startsWith(`${companyId}/`) ||
    isUnsafeStoragePath(modelPath)
  ) {
    throw new Error("Invalid model path");
  }

  const modelRecord = await client.from("modelUpload").insert({
    id: modelId,
    modelPath,
    name,
    size,
    // Frozen as-uploaded bytes: `size` is later overwritten with the compacted
    // (.zst) stored size, but the viewer's reduction badge compares the original.
    originalSize: size,
    // Frozen as-uploaded path: `modelPath` is later repointed at the compacted
    // artifact (STEP → `.xbf.zst`), but downloads must serve the original bytes.
    // Mesh compaction nulls this again (its `.zst` decompresses to the original).
    originalPath: modelPath,
    companyId,
    createdBy: userId
  });

  if (modelRecord.error) {
    throw new Error("Failed to record upload: " + modelRecord.error.message);
  }

  if (itemId) {
    await client
      .from("item")
      .update({ modelUploadId: modelId })
      .eq("id", itemId);
  }
  if (salesRfqLineId) {
    await client
      .from("salesRfqLine")
      .update({ modelUploadId: modelId })
      .eq("id", salesRfqLineId);
  }
  if (quoteLineId) {
    await client
      .from("quoteLine")
      .update({ modelUploadId: modelId })
      .eq("id", quoteLineId);
  }
  if (salesOrderLineId) {
    await client
      .from("salesOrderLine")
      .update({ modelUploadId: modelId })
      .eq("id", salesOrderLineId);
  }
  if (jobId) {
    await client.from("job").update({ modelUploadId: modelId }).eq("id", jobId);
  }

  // Thumbnail is generated by model-optimize on success (it renders the GLB the
  // optimise produces) — firing it here, before the GLB exists, always failed.

  // Conversion to assembly-instruction artifacts (GLB + graph) is lazy by
  // default: most uploaded models never become assemblies. Callers that will
  // render the model on the shop floor (e.g. BOP step model slides) opt in
  // with `convert` so the assembler service produces the fast-loading GLB up
  // front. Best-effort: STEP-only, skipped when the assembler is down — the
  // viewer falls back to parsing the raw model client-side.
  const isStep = [".step", ".stp"].some((ext) =>
    modelPath.toLowerCase().endsWith(ext)
  );
  if (convert && isStep && (await isAssemblerServiceHealthy())) {
    try {
      await trigger("assembly-convert", {
        companyId,
        modelUploadId: modelId,
        userId
      });
    } catch (err) {
      console.error("Failed to start model conversion", err);
    }
  }

  // Eager optimisation: the assembler's /v1/optimize turns a mesh model into a
  // compact optimised GLB. The job derives the format from the stored file and
  // skips non-mesh inputs, so trigger unconditionally. Independent of the lazy
  // assembly-convert path — most uploads never become assemblies but should
  // still be optimised.
  await trigger("model-optimize", {
    modelUploadId: modelId,
    companyId,
    userId
  });

  return {
    success: true
  };
}
