// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) Carbon Manufacturing Systems Corporation and contributors.
// Carbon (github.com/crbnos/carbon). Modified or adapted versions of this file,
// including ports, remain AGPLv3; serving them over a network requires releasing their source.

import type { ConformanceCheck, Violation } from "../check";

/**
 * RLS policies and the RLS/auth helper functions are authored only in
 * packages/database/src/authz (manifest + helpers/<name>.sql), and `authz sync` applies
 * them after migrations. A migration that creates or alters a policy, or defines, alters
 * or drops a managed helper, would be silently overwritten at the next sync — or, for a
 * helper, reintroduce exactly the drift the manifest exists to stop (a redefinition once
 * turned get_companies_with_employee_permission from STABLE back to VOLATILE).
 *
 * `DROP POLICY` stays allowed: dropping a column a policy uses needs the policy gone
 * first, and the next sync recreates the table's policies from the manifest.
 *
 * Only migrations after the manifest took over are checked; older ones are history.
 */
const SINCE = "20260927000000";

/**
 * The first line of a migration rendered from the manifest by `authz migration` — the WHOLE
 * line, equal to GENERATED_HEADER in packages/database/src/authz/migration.ts (pinned by this
 * check's test). Those files carry policy and helper DDL on purpose, and @carbon/database's
 * migration.test.ts verifies the contents of exactly the files that start with that full line.
 * Matching only a prefix here let a hand-written file with an edited suffix skip both.
 */
export const GENERATED_AUTHZ_MIGRATION =
  "-- Generated by `pnpm --filter @carbon/database authz migration` from packages/database/src/authz. Do not edit.";

const NAME = String.raw`(?:(?:"?public"?)\s*\.\s*)?"?(\w+)"?`;
// The target may be on a later line; group 2 is its schema, when it names one. The manifest
// owns public tables only, so storage.objects (bucket) policies stay in migrations.
const POLICY_DDL =
  /\b(?:CREATE|ALTER)\s+POLICY\s+(?:"[^"]*"|\S+)\s+ON\s+(?:"?(\w+)"?\s*\.\s*)?"?\w+"?/gi;
const FUNCTION_DDL = new RegExp(
  String.raw`\b(CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION|ALTER\s+FUNCTION|DROP\s+FUNCTION(?:\s+IF\s+EXISTS)?)\s+${NAME}`,
  "gi"
);

/** Blank out comments, keeping newlines so line numbers stay right. */
const stripComments = (sql: string) =>
  sql
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
    .replace(/--[^\n]*/g, (m) => " ".repeat(m.length));

export const noAuthzDdlInMigrations = (
  helpers: string[]
): ConformanceCheck => ({
  id: "no-authz-ddl-in-migrations",
  description:
    "Policies and RLS helpers are authored in packages/database/src/authz, not migrations.",
  provenance: {
    deprecates: "CREATE/ALTER POLICY and managed helper DDL in migrations",
    replacedBy: "packages/database/src/authz (manifest.ts + helpers/*.sql)",
    since: SINCE
  },
  scan(file, contents) {
    const timestamp = /^(\d{14})_/.exec(file)?.[1];
    if (
      !timestamp ||
      timestamp < SINCE ||
      contents.startsWith(GENERATED_AUTHZ_MIGRATION)
    )
      return [];

    const managed = new Set(helpers.map((h) => h.toLowerCase()));
    const sql = stripComments(contents);
    const line = (index: number) => sql.slice(0, index).split("\n").length;
    const violations: Violation[] = [];
    for (const m of sql.matchAll(POLICY_DDL)) {
      if ((m[1] ?? "public").toLowerCase() !== "public") continue;
      violations.push({
        file,
        line: line(m.index),
        snippet: m[0].split("\n")[0] ?? m[0],
        message:
          "Author policies in packages/database/src/authz/manifest.ts, then run `pnpm --filter @carbon/database authz migration <name>`."
      });
    }
    for (const m of sql.matchAll(FUNCTION_DDL)) {
      if (!managed.has((m[2] ?? "").toLowerCase())) continue;
      violations.push({
        file,
        line: line(m.index),
        snippet: m[0],
        message: `${m[2]} is a managed helper; edit packages/database/src/authz/helpers/${m[2]}.sql, then run \`pnpm --filter @carbon/database authz migration <name>\`.`
      });
    }
    return violations;
  }
});
